FROM ubuntu:22.04

# https://openwrt.org/docs/guide-developer/toolchain/install-buildsystem
RUN echo $(nproc) && \
    apt update && \
    apt install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
                        gettext git libncurses5-dev libssl-dev python3-distutils rsync unzip \
                        zlib1g-dev file wget && \
    apt clean && \
    rm -rf /var/lib/apt/list/*
