FROM ubuntu:22.04

# https://openwrt.org/docs/guide-developer/toolchain/install-buildsystem
RUN sudo apt update && \
    sudo apt install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
      gettext git libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev file wget && \
    sudo apt clean && \
    sudo rm -rf /var/lib/apt/list/*
