FROM registry.cn-beijing.aliyuncs.com/licsber/github:openwrt-lede-env
LABEL org.opencontainers.image.authors="licsber<admin@licsber.site>"

USER licsber
WORKDIR /home/licsber/lede

RUN rm -rf bin
COPY --chown=licsber openwrt.lede.x86.config .config

RUN ./scripts/feeds update -a && \
    ./scripts/feeds install -a

RUN make defconfig && \
    make download -j8

RUN echo `nproc` && make -j || make -j1 V=s && \
    echo $?

CMD ['bash']
