name: LEDE Docker Image

on:
  push:
    branches: [ 'main' ]
    tags: [ 'v*.*.*' ]

env:
  REGISTRY: registry.cn-beijing.aliyuncs.com
  NAMESPACE: licsber
  REPOSITORY: github

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout V3 
      uses: actions/checkout@v3

    - name: Login to ACR V1
      uses: aliyun/acr-login@v1
      with:
        login-server: https://${{ env.REGISTRY }}
        username: "${{ secrets.ACR_USERNAME }}"
        password: "${{ secrets.ACR_PASSWD }}"

    - name: Build Base Image
      env:
        TAG: ${{ github.sha }}
      run: |
        IMAGE=${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.REPOSITORY }}:${{ env.REPOSITORY }}
        echo $IMAGE
        docker build -t "$IMAGE" --file Dockerfile.lede .
        docker push "$IMAGE"
