name: Self Win N11

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */8 * * *'

env:
  DOCKERFILE: openwrt/openwrt/n11/Dockerfile.openwrt-n11
  REGION: cn-beijing
  REGISTRY: registry.cn-beijing.aliyuncs.com
  NAMESPACE: licsber
  REPOSITORY: github
  TAG: win-openwrt-n11
  TAG_FULL: win-openwrt-n11-${{ github.run_id }}

jobs:
  build:
    runs-on: [self-hosted, Windows]
    steps:
    - name: Checkout V4 
      uses: actions/checkout@v4

    - name: Login to ACR V1
      uses: aliyun/acr-login@v1
      with:
        login-server: "https://${{ env.REGISTRY }}"
        username: "${{ secrets.ACR_USERNAME }}"
        password: "${{ secrets.ACR_PASSWD }}"
        region-id: "${{ env.REGION }}"

    - name: Build Image
      run: |
        $IMAGE = "${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.REPOSITORY }}"
        $TAG = "${{ env.TAG }}"

        $BUILD_DIR = Split-Path -Parent "${{ env.DOCKERFILE }}"
        docker pull "${IMAGE}:openwrt-lede-env"
        docker build --no-cache -t "${IMAGE}:${TAG}" --file ${{ env.DOCKERFILE }} $BUILD_DIR

    - name: Push Image
      run: |
        $IMAGE = "${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.REPOSITORY }}"
        docker push "${IMAGE}:${{ env.TAG }}"
        docker tag "${IMAGE}:${{ env.TAG }}" "${IMAGE}:${{ env.TAG_FULL }}"
        docker push "${IMAGE}:${{ env.TAG_FULL }}"
