name: Self Win OpenWRT LEDE X86 Docker Image

on:
  workflow_dispatch:
  push:

env:
  DOCKERFILE: openwrt\lede\x86\Dockerfile.openwrt-lede-x86
  REGION: cn-beijing
  REGISTRY: registry.cn-beijing.aliyuncs.com
  NAMESPACE: licsber
  REPOSITORY: github
  TAG: win-openwrt-lede-x86
  TAG_FULL: win-openwrt-lede-x86-${{ github.run_id }}

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout V4 
      uses: actions/checkout@v4

    - name: Login to ACR V1
      uses: aliyun/acr-login@v1
      with:
        login-server: "https://${{ env.REGISTRY }}"
        username: "${{ secrets.ACR_USERNAME }}"
        password: "${{ secrets.ACR_PASSWD }}"
        region-id: "${{ env.REGION }}"

    - name: Build Image
      id: build
      run: |
        $IMAGE = "${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.REPOSITORY }}"
        $TAG = "${{ env.TAG }}"
        echo "image=$IMAGE" >> $GITHUB_OUTPUT

        $PWD = Get-Location
        $PWD = $PWD.Path
        $BUILD_DIR = Split-Path -Parent "${{ env.DOCKERFILE }}"
        $BUILD_DIR_FULL = Join-Path $PWD $BUILD_DIR
        echo $BUILD_DIR_FULL
        ls $BUILD_DIR_FULL
        cd $BUILD_DIR_FULL

        docker build -t "${IMAGE}:${TAG}" --file ${{ env.DOCKERFILE }} .

    - name: Push Image
      run: |
        docker push "${{ steps.build.outputs.image }}:${{ env.TAG }}"
        docker tag "${{ steps.build.outputs.image }}:${{ env.TAG }}" "${{ steps.build.outputs.image }}:${{ env.TAG_FULL }}"
        docker push "${{ steps.build.outputs.image }}:${{ env.TAG_FULL }}"
